pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    call-to-action-apartment-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 350
                                    height: 350
                                    positioning: center
                                    forceResize: true
                        medias:
                            '(max-width: 576px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 390
                                        height: 350
                                        positioning: center
                                        forceResize: true
                        name: call-to-action-apartment-thumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703219065
                        creationDate: 1702534826
                        preserveAnimation: false
