pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    card-apartment-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 760
                                    height: 705
                                    positioning: center
                                    forceResize: true
                        medias:
                            '(max-width: 576px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 576
                                        height: 625
                                        positioning: center
                                        forceResize: true
                            '(max-width: 768px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 768
                                        height: 705
                                        positioning: center
                                        forceResize: true
                        name: card-apartment-thumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1702538240
                        preserveAnimation: false
