pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    error-page-image-thumbnail:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 300
                                    forceResize: false
                        medias: {  }
                        name: error-page-image-thumbnail
                        description: 'Thumbnail for rendering images in error pages'
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1695299246
                        preserveAnimation: false
