pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    hero-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 2500
                                    height: 500
                                    positioning: center
                                    forceResize: true
                        medias:
                            '(max-width: 576px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 576
                                        height: 500
                                        positioning: center
                                        forceResize: true
                            '(max-width: 768px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 768
                                        height: 500
                                        positioning: center
                                        forceResize: true
                            '(max-width: 1024px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 1024
                                        height: 500
                                        positioning: center
                                        forceResize: true
                            '(max-width: 1600px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 1600
                                        height: 500
                                        positioning: center
                                        forceResize: true
                            '(max-width: 1800px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 1800
                                        height: 500
                                        positioning: center
                                        forceResize: true
                        name: hero-thumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1695906024
                        preserveAnimation: false
