pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    media-slider-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 767
                                    height: 432
                                    positioning: center
                                    forceResize: true
                        medias:
                            '(min-width: 768px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 925
                                        height: 520
                                        positioning: center
                                        forceResize: true
                        name: media-slider-thumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703855347
                        creationDate: 1701517179
                        preserveAnimation: false
