pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    news-teaser-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 400
                                    height: 300
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: news-teaser-thumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1702276933
                        preserveAnimation: false
