pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    partner-slider:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 400
                                    height: 150
                                    positioning: center
                                    forceResize: true
                        medias:
                            '(max-width: 576px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 576
                                        height: 200
                                        positioning: center
                                        forceResize: true
                            '(max-width: 768px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 384
                                        height: 150
                                        positioning: null
                                        forceResize: false
                            '(max-width: 1024px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 256
                                        height: 100
                                        positioning: center
                                        forceResize: true
                            '(max-width: 1268px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 317
                                        height: 100
                                        positioning: center
                                        forceResize: true
                            '(max-width: 1600px)':
                                -
                                    method: cover
                                    arguments:
                                        width: 400
                                        height: 150
                                        positioning: center
                                        forceResize: true
                        name: partner-slider
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1700800576
                        preserveAnimation: false
