pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    statements-icon:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 76
                                    height: 63
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: statements-icon
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: true
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1703060908
                        creationDate: 1698737219
                        preserveAnimation: false
