_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

product_routes:
    resource: "../src/Controller/ProductController.php"
    type: attribute
