pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        language: en
        valid_languages:
            - de
            - fr
            - it
        fallback_languages:
            de: ''
            fr: ''
            it: ''
        default_language: de
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: /404
            localized:
                de: /404
                fr: /404
                it: /404
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
